
const dotenv = require("dotenv");
dotenv.config();

const { BASE_URL, PORT, SECRET_KEY, DATABASE_PASSWORD, DATABASE_NAME, DATABASE_SERVER, DATABASE_USER, LIVE_URL, FIREBASE_PROJECT_ID, FIREBASE_PRIVATE_KEY_ID, FIREBASE_PRIVATE_KEY, FIREBASE_CLIENT_EMAIL, FIREBASE_CLIENT_ID, FIREBASE_CLIENT_X509_CERT_URL } = process.env;

module.exports = {
    BASE_URL,
    LIVE_URL,
    PORT,
    SECRET_KEY,
    DATABASE_PASSWORD,
    DATABASE_NAME,
    DATABASE_SERVER,
    DATABASE_USER,
    FIREBASE_PROJECT_ID,
    FIREBASE_PRIVATE_KEY_ID,
    FIREBASE_PRIVATE_KEY,
    FIREBASE_CLIENT_EMAIL,
    FIREBASE_CLIENT_ID,
    FIREBASE_CLIENT_X509_CERT_URL
}